services:
  fastapi-template-app:
    image: fastapi-template-app:latest
    hostname: fastapi-template/app
    container_name: fastapi-template-app
    restart: always
    volumes:
      - ./app:/app
    build:
      context: ./app
      dockerfile: Dockerfile
    command:
      ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@fastapi-template-db:5432/template

  fastapi-template-db:
    image: postgres:latest
    hostname: fastapi-template/db
    container_name: fastapi-template-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: template
    ports:
      - "5432:5432"
    volumes:
      - .pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
